import type { Metadata } from 'next';
import './globals.css';
import { Header } from '@/components/layout/Header';
import { MobileNav } from '@/components/layout/MobileNav';
import ContentInner from '@/components/layout/ContentInner';
import Providers from '@/providers/Providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <ContentInner>{children}</ContentInner>
          <MobileNav />
        </Providers>
      </body>
    </html>
  );
}
